import XRay from './xRay';
export { XRay };
import SES from './ses';
export { SES };
import ACMPCA from './acmpca';
export { ACMPCA };
import ServiceCatalog from './serviceCatalog';
export { ServiceCatalog };
import WAF from './waf';
export { WAF };
import IAM from './iam';
export { IAM };
import Backup from './backup';
export { Backup };
import AppIntegrations from './appIntegrations';
export { AppIntegrations };
import Rekognition from './rekognition';
export { Rekognition };
import Route53Resolver from './route53Resolver';
export { Route53Resolver };
import S3 from './s3';
export { S3 };
import EC2 from './ec2';
export { EC2 };
import Elasticsearch from './elasticsearch';
export { Elasticsearch };
import IoTSiteWise from './ioTSiteWise';
export { IoTSiteWise };
import LookoutMetrics from './lookoutMetrics';
export { LookoutMetrics };
import WAFRegional from './wafRegional';
export { WAFRegional };
import RAM from './ram';
export { RAM };
import Redshift from './redshift';
export { Redshift };
import Kinesis from './kinesis';
export { Kinesis };
import SageMaker from './sageMaker';
export { SageMaker };
import AppRunner from './appRunner';
export { AppRunner };
import AppSync from './appSync';
export { AppSync };
import DataSync from './dataSync';
export { DataSync };
import RefactorSpaces from './refactorSpaces';
export { RefactorSpaces };
import Pinpoint from './pinpoint';
export { Pinpoint };
import Route53 from './route53';
export { Route53 };
import Timestream from './timestream';
export { Timestream };
import ManagedBlockchain from './managedBlockchain';
export { ManagedBlockchain };
import ECS from './ecs';
export { ECS };
import Events from './events';
export { Events };
import NetworkManager from './networkManager';
export { NetworkManager };
import KinesisAnalytics from './kinesisAnalytics';
export { KinesisAnalytics };
import CloudFormation from './cloudFormation';
export { CloudFormation };
import Cognito from './cognito';
export { Cognito };
import AppStream from './appStream';
export { AppStream };
import Greengrass from './greengrass';
export { Greengrass };
import CloudFront from './cloudFront';
export { CloudFront };
import WAFv2 from './waFv2';
export { WAFv2 };
import LakeFormation from './lakeFormation';
export { LakeFormation };
import SNS from './sns';
export { SNS };
import QuickSight from './quickSight';
export { QuickSight };
import EKS from './eks';
export { EKS };
import AppMesh from './appMesh';
export { AppMesh };
import CE from './ce';
export { CE };
import IoT1Click from './ioT1Click';
export { IoT1Click };
import MediaConvert from './mediaConvert';
export { MediaConvert };
import IoT from './iot';
export { IoT };
import ApiGateway from './apiGateway';
export { ApiGateway };
import Lambda from './lambda';
export { Lambda };
import RDS from './rds';
export { RDS };
import MemoryDB from './memoryDb';
export { MemoryDB };
import IoTFleetHub from './ioTFleetHub';
export { IoTFleetHub };
import MWAA from './mwaa';
export { MWAA };
import GuardDuty from './guardDuty';
export { GuardDuty };
import Logs from './logs';
export { Logs };
import Lightsail from './lightsail';
export { Lightsail };
import Macie from './macie';
export { Macie };
import SecretsManager from './secretsManager';
export { SecretsManager };
import ElasticLoadBalancingV2 from './elasticLoadBalancingV2';
export { ElasticLoadBalancingV2 };
import CodeBuild from './codeBuild';
export { CodeBuild };
import DMS from './dms';
export { DMS };
import Connect from './connect';
export { Connect };
import StepFunctions from './stepFunctions';
export { StepFunctions };
import CodeDeploy from './codeDeploy';
export { CodeDeploy };
import CustomerProfiles from './customerProfiles';
export { CustomerProfiles };
import Location from './location';
export { Location };
import DAX from './dax';
export { DAX };
import ElastiCache from './elastiCache';
export { ElastiCache };
import EMR from './emr';
export { EMR };
import CodePipeline from './codePipeline';
export { CodePipeline };
import MediaConnect from './mediaConnect';
export { MediaConnect };
import SSMContacts from './ssmContacts';
export { SSMContacts };
import GreengrassV2 from './greengrassV2';
export { GreengrassV2 };
import IoTAnalytics from './ioTAnalytics';
export { IoTAnalytics };
import Amplify from './amplify';
export { Amplify };
import CloudWatch from './cloudWatch';
export { CloudWatch };
import Cloud9 from './cloud9';
export { Cloud9 };
import Lex from './lex';
export { Lex };
import IoTWireless from './ioTWireless';
export { IoTWireless };
import DocDB from './docDb';
export { DocDB };
import SSM from './ssm';
export { SSM };
import KinesisAnalyticsV2 from './kinesisAnalyticsV2';
export { KinesisAnalyticsV2 };
import ServiceDiscovery from './serviceDiscovery';
export { ServiceDiscovery };
import RoboMaker from './roboMaker';
export { RoboMaker };
import AutoScaling from './autoScaling';
export { AutoScaling };
import SSMIncidents from './ssmIncidents';
export { SSMIncidents };
import KMS from './kms';
export { KMS };
import Detective from './detective';
export { Detective };
import Synthetics from './synthetics';
export { Synthetics };
import DataBrew from './dataBrew';
export { DataBrew };
import ApiGatewayV2 from './apiGatewayV2';
export { ApiGatewayV2 };
import ECR from './ecr';
export { ECR };
import Glue from './glue';
export { Glue };
import OpsWorks from './opsWorks';
export { OpsWorks };
import Neptune from './neptune';
export { Neptune };
import MediaTailor from './mediaTailor';
export { MediaTailor };
import ResilienceHub from './resilienceHub';
export { ResilienceHub };
import MediaPackage from './mediaPackage';
export { MediaPackage };
import Transfer from './transfer';
export { Transfer };
import NetworkFirewall from './networkFirewall';
export { NetworkFirewall };
import CodeGuruReviewer from './codeGuruReviewer';
export { CodeGuruReviewer };
import ElasticBeanstalk from './elasticBeanstalk';
export { ElasticBeanstalk };
import WorkSpaces from './workSpaces';
export { WorkSpaces };
import IoTCoreDeviceAdvisor from './ioTCoreDeviceAdvisor';
export { IoTCoreDeviceAdvisor };
import ImageBuilder from './imageBuilder';
export { ImageBuilder };
import IoTThingsGraph from './ioTThingsGraph';
export { IoTThingsGraph };
import AutoScalingPlans from './autoScalingPlans';
export { AutoScalingPlans };
import SSO from './sso';
export { SSO };
import GameLift from './gameLift';
export { GameLift };
import APS from './aps';
export { APS };
import DirectoryService from './directoryService';
export { DirectoryService };
import Config from './config';
export { Config };
import Personalize from './personalize';
export { Personalize };
import LicenseManager from './licenseManager';
export { LicenseManager };
import Inspector from './inspector';
export { Inspector };
import EMRContainers from './emrContainers';
export { EMRContainers };
import RUM from './rum';
export { RUM };
import OpsWorksCM from './opsWorksCm';
export { OpsWorksCM };
import Batch from './batch';
export { Batch };
import KinesisVideo from './kinesisVideo';
export { KinesisVideo };
import S3Outposts from './s3Outposts';
export { S3Outposts };
import AppConfig from './appConfig';
export { AppConfig };
import FSx from './fSx';
export { FSx };
import DataPipeline from './dataPipeline';
export { DataPipeline };
import MediaLive from './mediaLive';
export { MediaLive };
import CodeArtifact from './codeArtifact';
export { CodeArtifact };
import Wisdom from './wisdom';
export { Wisdom };
import CodeGuruProfiler from './codeGuruProfiler';
export { CodeGuruProfiler };
import Athena from './athena';
export { Athena };
import IVS from './ivs';
export { IVS };
import SQS from './sqs';
export { SQS };
import CodeCommit from './codeCommit';
export { CodeCommit };
import MSK from './msk';
export { MSK };
import MediaStore from './mediaStore';
export { MediaStore };
import LookoutVision from './lookoutVision';
export { LookoutVision };
import EventSchemas from './eventSchemas';
export { EventSchemas };
import KinesisFirehose from './kinesisFirehose';
export { KinesisFirehose };
import ApplicationAutoScaling from './applicationAutoScaling';
export { ApplicationAutoScaling };
import Forecast from './forecast';
export { Forecast };
import DynamoDB from './dynamoDb';
export { DynamoDB };
import CertificateManager from './certificateManager';
export { CertificateManager };
import CodeStar from './codeStar';
export { CodeStar };
import Chatbot from './chatbot';
export { Chatbot };
import Cassandra from './cassandra';
export { Cassandra };
import GlobalAccelerator from './globalAccelerator';
export { GlobalAccelerator };
import AccessAnalyzer from './accessAnalyzer';
export { AccessAnalyzer };
import CodeStarConnections from './codeStarConnections';
export { CodeStarConnections };
import Budgets from './budgets';
export { Budgets };
import EFS from './efs';
export { EFS };
import NimbleStudio from './nimbleStudio';
export { NimbleStudio };
import ApplicationInsights from './applicationInsights';
export { ApplicationInsights };
import QLDB from './qldb';
export { QLDB };
import Evidently from './evidently';
export { Evidently };
import ElasticLoadBalancing from './elasticLoadBalancing';
export { ElasticLoadBalancing };
import AmazonMQ from './amazonMq';
export { AmazonMQ };
import S3ObjectLambda from './s3ObjectLambda';
export { S3ObjectLambda };
import CloudTrail from './cloudTrail';
export { CloudTrail };
import ServiceCatalogAppRegistry from './serviceCatalogAppRegistry';
export { ServiceCatalogAppRegistry };
import AmplifyUIBuilder from './amplifyUiBuilder';
export { AmplifyUIBuilder };
import FIS from './fis';
export { FIS };
import DevOpsGuru from './devOpsGuru';
export { DevOpsGuru };
import AuditManager from './auditManager';
export { AuditManager };
import DLM from './dlm';
export { DLM };
import SDB from './sdb';
export { SDB };
import IoTEvents from './ioTEvents';
export { IoTEvents };
import RedshiftServerless from './redshiftServerless';
export { RedshiftServerless };
import FMS from './fms';
export { FMS };
import CodeStarNotifications from './codeStarNotifications';
export { CodeStarNotifications };
import EMRServerless from './emrServerless';
export { EMRServerless };
import ASK from './ask';
export { ASK };
import AppFlow from './appFlow';
export { AppFlow };
import SecurityHub from './securityHub';
export { SecurityHub };
import Signer from './signer';
export { Signer };
import InspectorV2 from './inspectorV2';
export { InspectorV2 };
import ResourceGroups from './resourceGroups';
export { ResourceGroups };
import VoiceID from './voiceId';
export { VoiceID };
import KafkaConnect from './kafkaConnect';
export { KafkaConnect };
import OpenSearchService from './openSearchService';
export { OpenSearchService };
import LookoutEquipment from './lookoutEquipment';
export { LookoutEquipment };
import GroundStation from './groundStation';
export { GroundStation };
import PinpointEmail from './pinpointEmail';
export { PinpointEmail };
import FraudDetector from './fraudDetector';
export { FraudDetector };
import Panorama from './panorama';
export { Panorama };
import Kendra from './kendra';
export { Kendra };
import IoTTwinMaker from './ioTTwinMaker';
export { IoTTwinMaker };
import ConnectCampaigns from './connectCampaigns';
export { ConnectCampaigns };
import FinSpace from './finSpace';
export { FinSpace };
import BillingConductor from './billingConductor';
export { BillingConductor };
import Route53RecoveryReadiness from './route53RecoveryReadiness';
export { Route53RecoveryReadiness };
import Route53RecoveryControl from './route53RecoveryControl';
export { Route53RecoveryControl };
import HealthLake from './healthLake';
export { HealthLake };
import CUR from './cur';
export { CUR };
import DeviceFarm from './deviceFarm';
export { DeviceFarm };
declare const _default: {
    XRay: typeof XRay;
    SES: typeof SES;
    ACMPCA: typeof ACMPCA;
    ServiceCatalog: typeof ServiceCatalog;
    WAF: typeof WAF;
    IAM: typeof IAM;
    Backup: typeof Backup;
    AppIntegrations: typeof AppIntegrations;
    Rekognition: typeof Rekognition;
    Route53Resolver: typeof Route53Resolver;
    S3: typeof S3;
    EC2: typeof EC2;
    Elasticsearch: typeof Elasticsearch;
    IoTSiteWise: typeof IoTSiteWise;
    LookoutMetrics: typeof LookoutMetrics;
    WAFRegional: typeof WAFRegional;
    RAM: typeof RAM;
    Redshift: typeof Redshift;
    Kinesis: typeof Kinesis;
    SageMaker: typeof SageMaker;
    AppRunner: typeof AppRunner;
    AppSync: typeof AppSync;
    DataSync: typeof DataSync;
    RefactorSpaces: typeof RefactorSpaces;
    Pinpoint: typeof Pinpoint;
    Route53: typeof Route53;
    Timestream: typeof Timestream;
    ManagedBlockchain: typeof ManagedBlockchain;
    ECS: typeof ECS;
    Events: typeof Events;
    NetworkManager: typeof NetworkManager;
    KinesisAnalytics: typeof KinesisAnalytics;
    CloudFormation: typeof CloudFormation;
    Cognito: typeof Cognito;
    AppStream: typeof AppStream;
    Greengrass: typeof Greengrass;
    CloudFront: typeof CloudFront;
    WAFv2: typeof WAFv2;
    LakeFormation: typeof LakeFormation;
    SNS: typeof SNS;
    QuickSight: typeof QuickSight;
    EKS: typeof EKS;
    AppMesh: typeof AppMesh;
    CE: typeof CE;
    IoT1Click: typeof IoT1Click;
    MediaConvert: typeof MediaConvert;
    IoT: typeof IoT;
    ApiGateway: typeof ApiGateway;
    Lambda: typeof Lambda;
    RDS: typeof RDS;
    MemoryDB: typeof MemoryDB;
    IoTFleetHub: typeof IoTFleetHub;
    MWAA: typeof MWAA;
    GuardDuty: typeof GuardDuty;
    Logs: typeof Logs;
    Lightsail: typeof Lightsail;
    Macie: typeof Macie;
    SecretsManager: typeof SecretsManager;
    ElasticLoadBalancingV2: typeof ElasticLoadBalancingV2;
    CodeBuild: typeof CodeBuild;
    DMS: typeof DMS;
    Connect: typeof Connect;
    StepFunctions: typeof StepFunctions;
    CodeDeploy: typeof CodeDeploy;
    CustomerProfiles: typeof CustomerProfiles;
    Location: typeof Location;
    DAX: typeof DAX;
    ElastiCache: typeof ElastiCache;
    EMR: typeof EMR;
    CodePipeline: typeof CodePipeline;
    MediaConnect: typeof MediaConnect;
    SSMContacts: typeof SSMContacts;
    GreengrassV2: typeof GreengrassV2;
    IoTAnalytics: typeof IoTAnalytics;
    Amplify: typeof Amplify;
    CloudWatch: typeof CloudWatch;
    Cloud9: typeof Cloud9;
    Lex: typeof Lex;
    IoTWireless: typeof IoTWireless;
    DocDB: typeof DocDB;
    SSM: typeof SSM;
    KinesisAnalyticsV2: typeof KinesisAnalyticsV2;
    ServiceDiscovery: typeof ServiceDiscovery;
    RoboMaker: typeof RoboMaker;
    AutoScaling: typeof AutoScaling;
    SSMIncidents: typeof SSMIncidents;
    KMS: typeof KMS;
    Detective: typeof Detective;
    Synthetics: typeof Synthetics;
    DataBrew: typeof DataBrew;
    ApiGatewayV2: typeof ApiGatewayV2;
    ECR: typeof ECR;
    Glue: typeof Glue;
    OpsWorks: typeof OpsWorks;
    Neptune: typeof Neptune;
    MediaTailor: typeof MediaTailor;
    ResilienceHub: typeof ResilienceHub;
    MediaPackage: typeof MediaPackage;
    Transfer: typeof Transfer;
    NetworkFirewall: typeof NetworkFirewall;
    CodeGuruReviewer: typeof CodeGuruReviewer;
    ElasticBeanstalk: typeof ElasticBeanstalk;
    WorkSpaces: typeof WorkSpaces;
    IoTCoreDeviceAdvisor: typeof IoTCoreDeviceAdvisor;
    ImageBuilder: typeof ImageBuilder;
    IoTThingsGraph: typeof IoTThingsGraph;
    AutoScalingPlans: typeof AutoScalingPlans;
    SSO: typeof SSO;
    GameLift: typeof GameLift;
    APS: typeof APS;
    DirectoryService: typeof DirectoryService;
    Config: typeof Config;
    Personalize: typeof Personalize;
    LicenseManager: typeof LicenseManager;
    Inspector: typeof Inspector;
    EMRContainers: typeof EMRContainers;
    RUM: typeof RUM;
    OpsWorksCM: typeof OpsWorksCM;
    Batch: typeof Batch;
    KinesisVideo: typeof KinesisVideo;
    S3Outposts: typeof S3Outposts;
    AppConfig: typeof AppConfig;
    FSx: typeof FSx;
    DataPipeline: typeof DataPipeline;
    MediaLive: typeof MediaLive;
    CodeArtifact: typeof CodeArtifact;
    Wisdom: typeof Wisdom;
    CodeGuruProfiler: typeof CodeGuruProfiler;
    Athena: typeof Athena;
    IVS: typeof IVS;
    SQS: typeof SQS;
    CodeCommit: typeof CodeCommit;
    MSK: typeof MSK;
    MediaStore: typeof MediaStore;
    LookoutVision: typeof LookoutVision;
    EventSchemas: typeof EventSchemas;
    KinesisFirehose: typeof KinesisFirehose;
    ApplicationAutoScaling: typeof ApplicationAutoScaling;
    Forecast: typeof Forecast;
    DynamoDB: typeof DynamoDB;
    CertificateManager: typeof CertificateManager;
    CodeStar: typeof CodeStar;
    Chatbot: typeof Chatbot;
    Cassandra: typeof Cassandra;
    GlobalAccelerator: typeof GlobalAccelerator;
    AccessAnalyzer: typeof AccessAnalyzer;
    CodeStarConnections: typeof CodeStarConnections;
    Budgets: typeof Budgets;
    EFS: typeof EFS;
    NimbleStudio: typeof NimbleStudio;
    ApplicationInsights: typeof ApplicationInsights;
    QLDB: typeof QLDB;
    Evidently: typeof Evidently;
    ElasticLoadBalancing: typeof ElasticLoadBalancing;
    AmazonMQ: typeof AmazonMQ;
    S3ObjectLambda: typeof S3ObjectLambda;
    CloudTrail: typeof CloudTrail;
    ServiceCatalogAppRegistry: typeof ServiceCatalogAppRegistry;
    AmplifyUIBuilder: typeof AmplifyUIBuilder;
    FIS: typeof FIS;
    DevOpsGuru: typeof DevOpsGuru;
    AuditManager: typeof AuditManager;
    DLM: typeof DLM;
    SDB: typeof SDB;
    IoTEvents: typeof IoTEvents;
    RedshiftServerless: typeof RedshiftServerless;
    FMS: typeof FMS;
    CodeStarNotifications: typeof CodeStarNotifications;
    EMRServerless: typeof EMRServerless;
    ASK: typeof ASK;
    AppFlow: typeof AppFlow;
    SecurityHub: typeof SecurityHub;
    Signer: typeof Signer;
    InspectorV2: typeof InspectorV2;
    ResourceGroups: typeof ResourceGroups;
    VoiceID: typeof VoiceID;
    KafkaConnect: typeof KafkaConnect;
    OpenSearchService: typeof OpenSearchService;
    LookoutEquipment: typeof LookoutEquipment;
    GroundStation: typeof GroundStation;
    PinpointEmail: typeof PinpointEmail;
    FraudDetector: typeof FraudDetector;
    Panorama: typeof Panorama;
    Kendra: typeof Kendra;
    IoTTwinMaker: typeof IoTTwinMaker;
    ConnectCampaigns: typeof ConnectCampaigns;
    FinSpace: typeof FinSpace;
    BillingConductor: typeof BillingConductor;
    Route53RecoveryReadiness: typeof Route53RecoveryReadiness;
    Route53RecoveryControl: typeof Route53RecoveryControl;
    HealthLake: typeof HealthLake;
    CUR: typeof CUR;
    DeviceFarm: typeof DeviceFarm;
};
export default _default;
